/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.17
 * Generated at: 2019-05-01 16:57:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class modify_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/views/board/../includes/footer.jsp", Long.valueOf(1556618730182L));
    _jspx_dependants.put("jar:file:/C:/Users/min/Desktop/min/Codingdan/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ex02/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/board/../includes/header.jsp", Long.valueOf(1556620997895L));
    _jspx_dependants.put("jar:file:/C:/Users/min/Desktop/min/Codingdan/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ex02/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1546426475484L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("<!--  -->\r\n");
      out.write("<title>Codingdan</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Custom fonts for this template -->\r\n");
      out.write("<link href=\"/resources/vendor/fontawesome-free/css/all.min.css\"\r\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Custom styles for this template -->\r\n");
      out.write("<link href=\"/resources/css/sb-admin-2.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Custom styles for this page -->\r\n");
      out.write("<link href=\"/resources/vendor/datatables/dataTables.bootstrap4.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body id=\"page-top\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Page Wrapper -->\r\n");
      out.write("\t<div id=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Sidebar -->\r\n");
      out.write("\t\t<ul\r\n");
      out.write("\t\t\tclass=\"navbar-nav bg-gradient-primary sidebar sidebar-dark accordion\"\r\n");
      out.write("\t\t\tid=\"accordionSidebar\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Sidebar - Brand -->\r\n");
      out.write("\t\t\t<a\r\n");
      out.write("\t\t\t\tclass=\"sidebar-brand d-flex align-items-center justify-content-center\"\r\n");
      out.write("\t\t\t\thref=\"index.html\">\r\n");
      out.write("\t\t\t\t<div class=\"sidebar-brand-icon rotate-n-15\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fas fa-laugh-wink\"></i>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"sidebar-brand-text mx-3\">\r\n");
      out.write("\t\t\t\t\tSB Admin <sup>2</sup>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Divider -->\r\n");
      out.write("\t\t\t<hr class=\"sidebar-divider my-0\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Nav Item - Dashboard -->\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"index.html\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fas fa-fw fa-tachometer-alt\"></i> <span>Dashboard</span>\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Divider -->\r\n");
      out.write("\t\t\t<hr class=\"sidebar-divider\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Heading -->\r\n");
      out.write("\t\t\t<div class=\"sidebar-heading\">Interface</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Nav Item - Pages Collapse Menu -->\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link collapsed\" href=\"#\"\r\n");
      out.write("\t\t\t\tdata-toggle=\"collapse\" data-target=\"#collapseTwo\"\r\n");
      out.write("\t\t\t\taria-expanded=\"true\" aria-controls=\"collapseTwo\"> <i\r\n");
      out.write("\t\t\t\t\tclass=\"fas fa-fw fa-cog\"></i> <span>Components</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t\t<div id=\"collapseTwo\" class=\"collapse\" aria-labelledby=\"headingTwo\"\r\n");
      out.write("\t\t\t\t\tdata-parent=\"#accordionSidebar\">\r\n");
      out.write("\t\t\t\t\t<div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("\t\t\t\t\t\t<h6 class=\"collapse-header\">Custom Components:</h6>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" href=\"buttons.html\">Buttons</a> <a\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"collapse-item\" href=\"cards.html\">Cards</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Nav Item - Utilities Collapse Menu -->\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link collapsed\" href=\"#\"\r\n");
      out.write("\t\t\t\tdata-toggle=\"collapse\" data-target=\"#collapseUtilities\"\r\n");
      out.write("\t\t\t\taria-expanded=\"true\" aria-controls=\"collapseUtilities\"> <i\r\n");
      out.write("\t\t\t\t\tclass=\"fas fa-fw fa-wrench\"></i> <span>Utilities</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t\t<div id=\"collapseUtilities\" class=\"collapse\"\r\n");
      out.write("\t\t\t\t\taria-labelledby=\"headingUtilities\" data-parent=\"#accordionSidebar\">\r\n");
      out.write("\t\t\t\t\t<div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("\t\t\t\t\t\t<h6 class=\"collapse-header\">Custom Utilities:</h6>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" href=\"utilities-color.html\">Colors</a> <a\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"collapse-item\" href=\"utilities-border.html\">Borders</a> <a\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"collapse-item\" href=\"utilities-animation.html\">Animations</a>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" href=\"utilities-other.html\">Other</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Divider -->\r\n");
      out.write("\t\t\t<hr class=\"sidebar-divider\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Heading -->\r\n");
      out.write("\t\t\t<div class=\"sidebar-heading\">Addons</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Nav Item - Pages Collapse Menu -->\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link collapsed\" href=\"#\"\r\n");
      out.write("\t\t\t\tdata-toggle=\"collapse\" data-target=\"#collapsePages\"\r\n");
      out.write("\t\t\t\taria-expanded=\"true\" aria-controls=\"collapsePages\"> <i\r\n");
      out.write("\t\t\t\t\tclass=\"fas fa-fw fa-folder\"></i> <span>Pages</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t\t<div id=\"collapsePages\" class=\"collapse\"\r\n");
      out.write("\t\t\t\t\taria-labelledby=\"headingPages\" data-parent=\"#accordionSidebar\">\r\n");
      out.write("\t\t\t\t\t<div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("\t\t\t\t\t\t<h6 class=\"collapse-header\">Login Screens:</h6>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" href=\"login.html\">Login</a> <a\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"collapse-item\" href=\"register.html\">Register</a> <a\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"collapse-item\" href=\"forgot-password.html\">Forgot\r\n");
      out.write("\t\t\t\t\t\t\tPassword</a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"collapse-divider\"></div>\r\n");
      out.write("\t\t\t\t\t\t<h6 class=\"collapse-header\">Other Pages:</h6>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"collapse-item\" href=\"404.html\">404 Page</a> <a\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"collapse-item\" href=\"blank.html\">Blank Page</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Nav Item - Charts -->\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"charts.html\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fas fa-fw fa-chart-area\"></i> <span>Charts</span>\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Nav Item - Tables -->\r\n");
      out.write("\t\t\t<li class=\"nav-item active\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\thref=\"tables.html\"> <i class=\"fas fa-fw fa-table\"></i> <span>Tables</span></a>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Divider -->\r\n");
      out.write("\t\t\t<hr class=\"sidebar-divider d-none d-md-block\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Sidebar Toggler (Sidebar) -->\r\n");
      out.write("\t\t\t<div class=\"text-center d-none d-md-inline\">\r\n");
      out.write("\t\t\t\t<button class=\"rounded-circle border-0\" id=\"sidebarToggle\"></button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<!-- End of Sidebar -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Content Wrapper -->\r\n");
      out.write("\t\t<div id=\"content-wrapper\" class=\"d-flex flex-column\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Main Content -->\r\n");
      out.write("\t\t\t<div id=\"content\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Topbar -->\r\n");
      out.write("\t\t\t\t<nav\r\n");
      out.write("\t\t\t\t\tclass=\"navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Sidebar Toggle (Topbar) -->\r\n");
      out.write("\t\t\t\t\t<button id=\"sidebarToggleTop\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"btn btn-link d-md-none rounded-circle mr-3\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-bars\"></i>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Topbar Search -->\r\n");
      out.write("\t\t\t\t\t<form\r\n");
      out.write("\t\t\t\t\t\tclass=\"d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control bg-light border-0 small\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Search for...\" aria-label=\"Search\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-describedby=\"basic-addon2\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"input-group-append\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"btn btn-primary\" type=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fas fa-search fa-sm\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Topbar Navbar -->\r\n");
      out.write("\t\t\t\t\t<ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Nav Item - Search Dropdown (Visible Only XS) -->\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item dropdown no-arrow d-sm-none\"><a\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\" id=\"searchDropdown\"\r\n");
      out.write("\t\t\t\t\t\t\trole=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\taria-expanded=\"false\"> <i class=\"fas fa-search fa-fw\"></i>\r\n");
      out.write("\t\t\t\t\t\t</a> <!-- Dropdown - Messages -->\r\n");
      out.write("\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-labelledby=\"searchDropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<form class=\"form-inline mr-auto w-100 navbar-search\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control bg-light border-0 small\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Search for...\" aria-label=\"Search\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\taria-describedby=\"basic-addon2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"input-group-append\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-primary\" type=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fas fa-search fa-sm\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Nav Item - Alerts -->\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item dropdown no-arrow mx-1\"><a\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\" id=\"alertsDropdown\"\r\n");
      out.write("\t\t\t\t\t\t\trole=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\taria-expanded=\"false\"> <i class=\"fas fa-bell fa-fw\"></i> <!-- Counter - Alerts -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"badge badge-danger badge-counter\">3+</span>\r\n");
      out.write("\t\t\t\t\t\t</a> <!-- Dropdown - Alerts -->\r\n");
      out.write("\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-labelledby=\"alertsDropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h6 class=\"dropdown-header\">Alerts Center</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"mr-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"icon-circle bg-primary\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"fas fa-file-alt text-white\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"small text-gray-500\">December 12, 2019</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"font-weight-bold\">A new monthly report is\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tready to download!</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a> <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"mr-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"icon-circle bg-success\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"fas fa-donate text-white\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"small text-gray-500\">December 7, 2019</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$290.29 has been deposited into your account!\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a> <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"mr-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"icon-circle bg-warning\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"fas fa-exclamation-triangle text-white\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"small text-gray-500\">December 2, 2019</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tSpending Alert: We've noticed unusually high spending for your\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\taccount.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a> <a class=\"dropdown-item text-center small text-gray-500\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"#\">Show All Alerts</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Nav Item - Messages -->\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item dropdown no-arrow mx-1\"><a\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\" id=\"messagesDropdown\"\r\n");
      out.write("\t\t\t\t\t\t\trole=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\taria-expanded=\"false\"> <i class=\"fas fa-envelope fa-fw\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Counter - Messages --> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"badge badge-danger badge-counter\">7</span>\r\n");
      out.write("\t\t\t\t\t\t</a> <!-- Dropdown - Messages -->\r\n");
      out.write("\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-labelledby=\"messagesDropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h6 class=\"dropdown-header\">Message Center</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"dropdown-list-image mr-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img class=\"rounded-circle\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsrc=\"https://source.unsplash.com/fn_BT9fwg_E/60x60\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"status-indicator bg-success\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"font-weight-bold\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"text-truncate\">Hi there! I am wondering if\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tyou can help me with a problem I've been having.</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"small text-gray-500\">Emily Fowler · 58m</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a> <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"dropdown-list-image mr-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img class=\"rounded-circle\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsrc=\"https://source.unsplash.com/AU4VPcFN4LE/60x60\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"status-indicator\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"text-truncate\">I have the photos that you\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tordered last month, how would you like them sent to you?</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"small text-gray-500\">Jae Chun · 1d</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a> <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"dropdown-list-image mr-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img class=\"rounded-circle\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsrc=\"https://source.unsplash.com/CS2uCrpNzJY/60x60\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"status-indicator bg-warning\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"text-truncate\">Last month's report looks\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tgreat, I am very happy with the progress so far, keep up the\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tgood work!</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"small text-gray-500\">Morgan Alvarez · 2d</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a> <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"dropdown-list-image mr-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img class=\"rounded-circle\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsrc=\"https://source.unsplash.com/Mv9hjnEUHR4/60x60\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"status-indicator bg-success\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"text-truncate\">Am I a good boy? The reason I\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\task is because someone told me that people say this to all\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdogs, even if they aren't good...</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"small text-gray-500\">Chicken the Dog · 2w</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a> <a class=\"dropdown-item text-center small text-gray-500\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"#\">Read More Messages</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"topbar-divider d-none d-sm-block\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Nav Item - User Information -->\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item dropdown no-arrow\"><a\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\" id=\"userDropdown\"\r\n");
      out.write("\t\t\t\t\t\t\trole=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\taria-expanded=\"false\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"mr-2 d-none d-lg-inline text-gray-600 small\">Valerie\r\n");
      out.write("\t\t\t\t\t\t\t\t\tLuna</span> <img class=\"img-profile rounded-circle\"\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"https://source.unsplash.com/QAB-WJcbgJk/60x60\">\r\n");
      out.write("\t\t\t\t\t\t</a> <!-- Dropdown - User Information -->\r\n");
      out.write("\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"dropdown-menu dropdown-menu-right shadow animated--grow-in\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-labelledby=\"userDropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"#\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fas fa-user fa-sm fa-fw mr-2 text-gray-400\"></i> Profile\r\n");
      out.write("\t\t\t\t\t\t\t\t</a> <a class=\"dropdown-item\" href=\"#\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fas fa-cogs fa-sm fa-fw mr-2 text-gray-400\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\tSettings\r\n");
      out.write("\t\t\t\t\t\t\t\t</a> <a class=\"dropdown-item\" href=\"#\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fas fa-list fa-sm fa-fw mr-2 text-gray-400\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\tActivity Log\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"dropdown-divider\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"#\" data-toggle=\"modal\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-target=\"#logoutModal\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\tLogout\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t<!-- End of Topbar -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- header에 jQuery 라이브러리를 추가하여 JSP에서 jQuery 사용을 편리하게 해준다 -->\r\n");
      out.write("\t\t\t\t<script\r\n");
      out.write("\t\t\t\t\tsrc=\"http://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t<h1 class=\"page-header\">Board Register</h1>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- input이나 textarea 태그의 name 속성은 BaordVO 클래스의 변수명과 일치시켜야 한다 -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t<div class=\"panel-heading\">Board Modify Page</div>\r\n");
      out.write("\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<form role=\"form\" action=\"/board/modify\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- 페이지 번호 유지를 위한 파라미터 추가 -->\r\n");
      out.write("\t\t\t\t\t<input type='hidden' name='pageNum'\r\n");
      out.write("\t\t\t\t\t\tvalue='");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("'> <input\r\n");
      out.write("\t\t\t\t\t\ttype='hidden' name='amount'\r\n");
      out.write("\t\t\t\t\t\tvalue='");
      if (_jspx_meth_c_005fout_005f1(_jspx_page_context))
        return;
      out.write("'>\r\n");
      out.write("\t\t\t\t\t\t<!-- 검색 조건 유지를 위한 파라미터 추가 -->\r\n");
      out.write("\t\t\t\t\t<input type='hidden' name='keyword' value='");
      if (_jspx_meth_c_005fout_005f2(_jspx_page_context))
        return;
      out.write("'>\r\n");
      out.write("\t\t\t\t\t<input type='hidden' name='type' value='");
      if (_jspx_meth_c_005fout_005f3(_jspx_page_context))
        return;
      out.write("'>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label>Bno</label><input class=\"form-control\" name='bno'\r\n");
      out.write("\t\t\t\t\t\t\tvalue='");
      if (_jspx_meth_c_005fout_005f4(_jspx_page_context))
        return;
      out.write("' readonly=\"readonly\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label>Title</label><input class=\"form-control\" name='title'\r\n");
      out.write("\t\t\t\t\t\t\tvalue='");
      if (_jspx_meth_c_005fout_005f5(_jspx_page_context))
        return;
      out.write("'>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label>Text area</label>\r\n");
      out.write("\t\t\t\t\t\t<textarea class=\"form-control\" rows=\"3\" name='content'>");
      if (_jspx_meth_c_005fout_005f6(_jspx_page_context))
        return;
      out.write("</textarea>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label>Writer</label><input class=\"form-control\" name='writer'\r\n");
      out.write("\t\t\t\t\t\t\tvalue='");
      if (_jspx_meth_c_005fout_005f7(_jspx_page_context))
        return;
      out.write("' readonly=\"readonly\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label>RegDate</label> <input class=\"form-control\" name='regDate'\r\n");
      out.write("\t\t\t\t\t\t\tvalue='");
      if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_page_context))
        return;
      out.write("'\r\n");
      out.write("\t\t\t\t\t\t\treadonly=\"readonly\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label>Update Date</label> <input class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\tname='updateDate'\r\n");
      out.write("\t\t\t\t\t\t\tvalue='");
      if (_jspx_meth_fmt_005fformatDate_005f1(_jspx_page_context))
        return;
      out.write("'\r\n");
      out.write("\t\t\t\t\t\t\treadonly=\"readonly\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<button type=\"submit\" data-oper='modify' class=\"btn btn-default\">Modify</button>\r\n");
      out.write("\t\t\t\t\t<button type=\"submit\" data-oper='remove' class=\"btn btn-danger\">Remove</button>\r\n");
      out.write("\t\t\t\t\t<button type=\"submit\" data-oper='list' class=\"btn btn-info\">List</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\r\n");
      out.write("\t\tvar formObj = $(\"form\");\r\n");
      out.write("\r\n");
      out.write("\t\t$('button').on(\"click\", function(e) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 모든 버튼은 기본적으로 submit 처리가 되므로, 이 동작을 막고 마지막에 직접 submit 처리를 해준다\r\n");
      out.write("\t\t\te.preventDefault();\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar operation = $(this).data(\"oper\");\r\n");
      out.write("\r\n");
      out.write("\t\t\tconsole.log(operation);\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (operation === 'remove') {\r\n");
      out.write("\t\t\t\tformObj.attr(\"action\", \"/board/remove\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t} else if (operation === 'list') {\r\n");
      out.write("\t\t\t\t// 목록으로 이동\r\n");
      out.write("\t\t\t\tformObj.attr(\"action\", \"/board/list\").attr(\"method\", \"get\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t// 필요한 파라미터만 복사해서 보관\r\n");
      out.write("\t\t\t\t// 페이징\r\n");
      out.write("\t\t\t\tvar pageNumTag = $(\"input[name='pageNum']\").clone();\r\n");
      out.write("\t\t\t\tvar amountTag = $(\"input[name='amount']\").clone();\r\n");
      out.write("\t\t\t\t// 검색\r\n");
      out.write("\t\t\t\tvar keywordTag = $(\"input[name='keyword']\").clone();\r\n");
      out.write("\t\t\t\tvar typeTag = $(\"input[name='type']\").clone();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t// list로 이동할 때는 form 태그의 모든 내용은 삭제한 상태에서,\r\n");
      out.write("\t\t\t\tformObj.empty();\r\n");
      out.write("\t\t\t\t// 필요한 태그만 추가한 뒤 submit\r\n");
      out.write("\t\t\t\tformObj.append(pageNumTag);\r\n");
      out.write("\t\t\t\tformObj.append(amountTag);\r\n");
      out.write("\t\t\t\tformObj.append(keywordTag);\r\n");
      out.write("\t\t\t\tformObj.append(typeTag);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tformObj.submit();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("<footer class=\"sticky-footer bg-white\">\r\n");
      out.write("\t<div class=\"container my-auto\">\r\n");
      out.write("\t\t<div class=\"copyright text-center my-auto\">\r\n");
      out.write("\t\t\t<span>Copyright &copy; Your Website 2019</span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</footer>\r\n");
      out.write("<!-- End of Footer -->\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<!-- End of Content Wrapper -->\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- End of Page Wrapper -->\r\n");
      out.write("\r\n");
      out.write("<!-- Scroll to Top Button-->\r\n");
      out.write("<a class=\"scroll-to-top rounded\" href=\"#page-top\"> <i\r\n");
      out.write("\tclass=\"fas fa-angle-up\"></i>\r\n");
      out.write("</a>\r\n");
      out.write("\r\n");
      out.write("<!-- Logout Modal-->\r\n");
      out.write("<div class=\"modal fade\" id=\"logoutModal\" tabindex=\"-1\" role=\"dialog\"\r\n");
      out.write("\taria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("\t<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t<h5 class=\"modal-title\" id=\"exampleModalLabel\">Ready to Leave?</h5>\r\n");
      out.write("\t\t\t\t<button class=\"close\" type=\"button\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\taria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t<span aria-hidden=\"true\">Ã</span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"modal-body\">Select \"Logout\" below if you are ready\r\n");
      out.write("\t\t\t\tto end your current session.</div>\r\n");
      out.write("\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t<button class=\"btn btn-secondary\" type=\"button\" data-dismiss=\"modal\">Cancel</button>\r\n");
      out.write("\t\t\t\t<a class=\"btn btn-primary\" href=\"login.html\">Logout</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap core JavaScript-->\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery ë¼ì´ë¸ë¬ë¦¬ë¥¼ headerë¡ ì®ê²¨ì¤ë¤: ì±ë¥ì ì¡°ê¸ ìí´ì§ë§, JSPìì jQuery ì¬ì©ì´ í¨ì¬ í¸í´ì§ëê¹ -->\r\n");
      out.write("<!-- <script src=\"/resources/vendor/jquery/jquery.min.js\"></script> -->\r\n");
      out.write("\r\n");
      out.write("<script src=\"/resources/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Core plugin JavaScript-->\r\n");
      out.write("<script src=\"/resources/vendor/jquery-easing/jquery.easing.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Custom scripts for all pages-->\r\n");
      out.write("<script src=\"/resources/js/sb-admin-2.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Page level plugins -->\r\n");
      out.write("<script src=\"/resources/vendor/datatables/jquery.dataTables.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/vendor/datatables/dataTables.bootstrap4.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Page level custom scripts -->\r\n");
      out.write("<script src=\"/resources/js/demo/datatables-demo.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- ë°ìí ì¹ ì²ë¦¬: jQuery êµì²´ í ëª¨ë°ì¼ í¬ê¸°ìì ìë¡ê³ ì¹¨ ìì ë©ë´ê° í¼ì³ì§ë ë¬¸ì  í´ê²°ì ìí ì½ë -->\r\n");
      out.write("<script>\r\n");
      out.write("  \t$(document).ready(function(){\r\n");
      out.write("  \t\t$('#dataTables-example').DataTable({\r\n");
      out.write("  \t\t\tresponsive: true\r\n");
      out.write("  \t\t});\r\n");
      out.write("  \t\t$(\".sidebar-nav\")\r\n");
      out.write("  \t\t.attr(\"class\", \"sidebar-nav navbar-collapse collapse\")\r\n");
      out.write("  \t\t.attr(\"aria-expended\", 'false')\r\n");
      out.write("  \t\t.attr(\"style\", \"height:1px\");\r\n");
      out.write("  \t})\r\n");
      out.write("  </script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent(null);
      // /WEB-INF/views/board/modify.jsp(26,13) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cri.pageNum }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f1_reused = false;
    try {
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent(null);
      // /WEB-INF/views/board/modify.jsp(28,13) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cri.amount }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      _jspx_th_c_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f2 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f2_reused = false;
    try {
      _jspx_th_c_005fout_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f2.setParent(null);
      // /WEB-INF/views/board/modify.jsp(30,48) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cri.keyword }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f2 = _jspx_th_c_005fout_005f2.doStartTag();
      if (_jspx_th_c_005fout_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
      _jspx_th_c_005fout_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f3 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f3_reused = false;
    try {
      _jspx_th_c_005fout_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f3.setParent(null);
      // /WEB-INF/views/board/modify.jsp(31,45) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f3.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cri.type }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f3 = _jspx_th_c_005fout_005f3.doStartTag();
      if (_jspx_th_c_005fout_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f3);
      _jspx_th_c_005fout_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f4 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f4_reused = false;
    try {
      _jspx_th_c_005fout_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f4.setParent(null);
      // /WEB-INF/views/board/modify.jsp(35,14) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f4.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.bno }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f4 = _jspx_th_c_005fout_005f4.doStartTag();
      if (_jspx_th_c_005fout_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f4);
      _jspx_th_c_005fout_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f5 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f5_reused = false;
    try {
      _jspx_th_c_005fout_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f5.setParent(null);
      // /WEB-INF/views/board/modify.jsp(40,14) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f5.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.title }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f5 = _jspx_th_c_005fout_005f5.doStartTag();
      if (_jspx_th_c_005fout_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f5);
      _jspx_th_c_005fout_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f6 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f6_reused = false;
    try {
      _jspx_th_c_005fout_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f6.setParent(null);
      // /WEB-INF/views/board/modify.jsp(45,61) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f6.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.content }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f6 = _jspx_th_c_005fout_005f6.doStartTag();
      if (_jspx_th_c_005fout_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f6);
      _jspx_th_c_005fout_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f6, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f7 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f7_reused = false;
    try {
      _jspx_th_c_005fout_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f7.setParent(null);
      // /WEB-INF/views/board/modify.jsp(51,14) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f7.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.writer }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f7 = _jspx_th_c_005fout_005f7.doStartTag();
      if (_jspx_th_c_005fout_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f7);
      _jspx_th_c_005fout_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f7, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f0.setParent(null);
      // /WEB-INF/views/board/modify.jsp(56,14) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setPattern("yyyy/MM/dd");
      // /WEB-INF/views/board/modify.jsp(56,14) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.regdate }", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
      _jspx_th_fmt_005fformatDate_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f1_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f1.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f1.setParent(null);
      // /WEB-INF/views/board/modify.jsp(63,14) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f1.setPattern("yyyy/MM/dd");
      // /WEB-INF/views/board/modify.jsp(63,14) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f1.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.updateDate }", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_fmt_005fformatDate_005f1 = _jspx_th_fmt_005fformatDate_005f1.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f1);
      _jspx_th_fmt_005fformatDate_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f1, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f1_reused);
    }
    return false;
  }
}
